/*
 * generated by Xtext
 */
package at.ac.univie.cs.swa.soa.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ServiceDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return at.ac.univie.cs.swa.soa.ui.internal.ServiceDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return at.ac.univie.cs.swa.soa.ui.internal.ServiceDslActivator.getInstance().getInjector("at.ac.univie.cs.swa.soa.ServiceDsl");
	}
	
}
