/*
* generated by Xtext
*/
package at.ac.univie.cs.swa.soa.ui.contentassist;

import at.ac.univie.cs.swa.soa.ui.contentassist.AbstractServiceDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ServiceDslProposalProvider extends AbstractServiceDslProposalProvider {

}
