/*
* generated by Xtext
*/
package at.ac.univie.cs.swa.soa.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ServiceDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("at/ac/univie/cs/swa/soa/parser/antlr/internal/InternalServiceDsl.tokens");
	}
}
