/*
* generated by Xtext
*/
package at.ac.univie.cs.swa.soa.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import at.ac.univie.cs.swa.soa.services.SDLGrammarAccess;

public class SDLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SDLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected at.ac.univie.cs.swa.soa.parser.antlr.internal.InternalSDLParser createParser(XtextTokenStream stream) {
		return new at.ac.univie.cs.swa.soa.parser.antlr.internal.InternalSDLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "SDL";
	}
	
	public SDLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SDLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
