/*
* generated by Xtext
*/
package at.ac.univie.cs.swa.soa.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class ServiceDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
