/*
 * generated by Xtext
 */
package at.ac.univie.cs.swa.soa;

import at.ac.univie.cs.swa.soa.generator.IGenerator2;
import at.ac.univie.cs.swa.soa.generator.SDLGenerator;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SDLRuntimeModule extends at.ac.univie.cs.swa.soa.AbstractSDLRuntimeModule {
	public Class<? extends IGenerator2> bindIGenerator2()
	{
		return SDLGenerator.class;
	}

}
