/*
* generated by Xtext
*/
package at.ac.univie.cs.swa.soa;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SDLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return at.ac.univie.cs.swa.soa.ui.internal.SDLActivator.getInstance().getInjector("at.ac.univie.cs.swa.soa.SDL");
	}
	
}
