/*
 * generated by Xtext
 */
package at.ac.univie.cs.swa.soa;

import at.ac.univie.cs.swa.soa.generator.IGenerator2;
import at.ac.univie.cs.swa.soa.generator.ServiceDslGenerator;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ServiceDslRuntimeModule extends at.ac.univie.cs.swa.soa.AbstractServiceDslRuntimeModule {
	public Class<? extends IGenerator2> bindIGenerator2()
	{
		return ServiceDslGenerator.class;
	}
}
