/*
* generated by Xtext
*/
package at.ac.univie.cs.swa.soa.ui.contentassist;

import at.ac.univie.cs.swa.soa.ui.contentassist.AbstractSDLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SDLProposalProvider extends AbstractSDLProposalProvider {

}
